[package]
name = "google-oauth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
anyhow = "1.0.70"
reqwest = { version = "0.11.16", features = ["blocking"] }
lazy_static = "1.4.0"
jwt = "0.16.0"
base64 = "0.21.0"
sha256 = "1.1.3"
rsa = { version = "0.8.2", features = ["sha2"] }
hex = { version = "0.4.3" }
