[package]
name = "blocking"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
google-oauth = { path = "../..", features = ["blocking"] }
tokio = { version = "1.33.0", features = ["full"] }
